version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - LLM_PROVIDER=${LLM_PROVIDER:-ollama}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://host.docker.internal:11434}
      - OLLAMA_MODEL=${OLLAMA_MODEL:-qwen2.5-coder:7b-instruct-q4_K_M}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.0-flash}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - CACHE_TTL_SECONDS=${CACHE_TTL_SECONDS:-86400}
    volumes:
      - ./classifier/model:/app/classifier/model
      - ./classifier/data:/app/classifier/data
      - ./mlflow:/app/mlflow
      - ./data:/app/data
    depends_on:
      - chromadb
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000"
    volumes:
      - chromadb_data:/chroma/chroma

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes   

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.13.0
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0 --port 5000
    volumes:
      - ./mlflow:/mlflow

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
    # Montamos carpeta completa por compatibilidad con Docker Desktop en Windows
      # En Linux/AWS se puede montar el archivo directamente
      - ./observability:/etc/prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  chromadb_data:
  redis_data: